
# This file is part of the dinSettingsPlugin package.
# (c) DineCat, 2010 http://dinecat.com/
#
# For the full copyright and license information, please view the LICENSE file,
# that was distributed with this package, or see http://www.dinecat.com/din/license.html

# Plugin schema file for Doctrine
#
# @package     dinSettingsPlugin
# @subpackage  config.doctrine
# @author      Nicolay N. Zyk <relo.san@gmail.com>

#DinSettingsSet
DinSettingsSet:

    actAs:
        I18n:
            fields:         ['title', 'description']

    columns:
        id:                 { type: 'integer(4)', primary: true, autoincrement: true }
        application:        { type: 'string(50)', fixed: true }
        name:               { type: 'string(50)', fixed: true, notnull: true }
        is_enabled:         { type: 'boolean', notnull: true, default: true }
        title:              { type: 'string(150)', fixed: true }
        description:        { type: 'clob(65532)' }
        sequence:           { type: 'integer(4)' }

    indexes:
        name:               { fields: ['application', 'name'], type: 'unique' }


#DinSettingsTree
DinSettingsTree:

    actAs:
        I18n:
            fields:         ['title', 'description']
        NestedSet:          { hasManyRoots: true, rootColumnName: 'root_id' }

    columns:
        id:                 { type: 'integer(4)', primary: true, autoincrement: true }
        set_id:             { type: 'integer(4)', notnull: true }
        root_id:            { type: 'integer(4)' }
        name:               { type: 'string(50)', fixed: true, notnull: true }
        is_enabled:         { type: 'boolean', notnull: true, default: true }
        title:              { type: 'string(150)', fixed: true }
        description:        { type: 'clob(65532)' }

    indexes:
        enabled:            { fields: ['set_id', 'is_enabled'] }

    relations:
        DinSettingsSet:
            local:          'set_id'
            foreign:        'id'
            type:           'one'
            foreignType:    'many'
            alias:          'Set'
            foreignAlias:   'Trees'
            onDelete:       'CASCADE'


#DinSettingsParam
DinSettingsParam:

    actAs:
        I18n:
            fields:         ['title', 'description']

    columns:
        id:                 { type: 'integer(4)', primary: true, autoincrement: true }
        tree_id:            { type: 'integer(4)', notnull: true }
        name:               { type: 'string(50)', fixed: true, notnull: true }
        type:               { type: 'integer(1)', fixed: true, notnull: '1' }
        is_enabled:         { type: 'boolean', notnull: true, default: true }
        title:              { type: 'string(150)', fixed: true }
        description:        { type: 'clob(65532)' }
        value:              { type: 'clob' }

    indexes:
        enabled:            { fields: ['tree_id', 'is_enabled'] }

    relations:
        DinSettingsTree:
            local:          'tree_id'
            foreign:        'id'
            type:           'one'
            foreignType:    'many'
            alias:          'Tree'
            foreignAlias:   'Params'
            onDelete:       'CASCADE'

#EOF